services:
  cds-server:
    build: .
    command: uvicorn src.payer.cds_hooks_server:app --host 0.0.0.0 --port 3001 --reload
    ports:
      - "3001:3001"
    env_file: .env
    volumes:
      - ./src:/app/src

  dtr-server:
    build: .
    command: uvicorn src.payer.dtr_server:app --host 0.0.0.0 --port 3002 --reload
    ports:
      - "3002:3002"
    env_file: .env
    volumes:
      - ./src:/app/src

  pas-server:
    build: .
    command: uvicorn src.payer.pas_server:app --host 0.0.0.0 --port 3003 --reload
    ports:
      - "3003:3003"
    env_file: .env
    volumes:
      - ./src:/app/src
